#!/usr/bin/python3

if __name__ != '__main__':
    print('this file can only be run directly.')
    exit(-1)

with open('./pylam.py', 'w') as f3:
    with open('./lam.py', 'r') as f1:
        with open('./opt.py', 'r') as f2:
            f3.write('#!/usr/bin/python3\n\n')
            f3.write('# -- NOTE: Generated from opt.py --\n\n')
            f3.write(f2.read().removesuffix('main()\n'))
            f3.write('# -- NOTE: Generated from lam.py --\n\n')
            f3.write(f1.read())
            f3.write('\n\n# -- NOTE: DONE ---\nmain()\n\n')
            f3.write('# -- NOTE: Generated by script gen.py:\n\n')
            f3.flush()
            with open('./gen.py', 'r') as f4:
                f3.writelines(['# ' + l for l in f4.readlines()])
            f3.flush()
